default:
  image: node:latest

before_script:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store
  - pnpm install

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

build:
  stage: build
  script:
    - pnpx webpack
  except:
    - master
    - develop
    - merge_requests
    - tags

eslint:
  stage: test
  script:
    - pnpx eslint .

prettier:
  stage: test
  script:
    - pnpx prettier --check .

tsc:
  stage: test
  script:
    - pnpx tsc --noEmit

deploy:
  stage: deploy
  script:
    - ./scripts/build.sh
  only:
    - master
    - develop
    - merge_requests
    - tags
  artifacts:
    name: eldarya-enhancements
    expose_as: eldarya-enhancements
    paths:
      - dist/eldarya-enhancements.meta.js
      - dist/eldarya-enhancements.user.js
