image: node:latest

before_script:
  - curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
  - pnpm config set store-dir .pnpm-store
  - pnpm install

cache:
  key:
    files:
      - pnpm-lock.yaml
  paths:
    - .pnpm-store

variables:
  # https://github.com/webpack/webpack/issues/14532
  NODE_OPTIONS: --openssl-legacy-provider

build:
  stage: build
  script:
    - pnpx webpack
  except:
    - develop
    - master
    - merge_requests
    - tags

eslint:
  stage: test
  script:
    - pnpx eslint .

prettier:
  stage: test
  script:
    - pnpx prettier --check .

tsc:
  stage: test
  script:
    - pnpx tsc --noEmit
  # https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/56858
  allow_failure: true

deploy:
  stage: deploy
  only:
    - develop
    - master
    - merge_requests
    - tags
  script:
    - ./scripts/build.sh
  artifacts:
    name: eldarya-enhancements
    expose_as: eldarya-enhancements
    paths:
      - dist/eldarya-enhancements.meta.js
      - dist/eldarya-enhancements.min.user.js
      - dist/eldarya-enhancements.user.js

release:
  before_script: []
  cache: []
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: deploy
      artifacts: true
  only:
    - tags
  script:
    - "echo $CI_COMMIT_TAG: $CI_COMMIT_TITLE"
  stage: .post
  release:
    tag_name: "$CI_COMMIT_TAG"
    description: "$CI_COMMIT_MESSAGE"
    assets:
      links:
        - name: "eldarya-enhancements-$CI_COMMIT_TAG.meta.js"
          url: "https://gitlab.com/NatoBoram/eldarya-enhancements/-/jobs/artifacts/$CI_COMMIT_TAG/raw/dist/eldarya-enhancements.meta.js?job=deploy"
          link_type: "other"
        - name: "eldarya-enhancements-$CI_COMMIT_TAG.min.user.js"
          url: "https://gitlab.com/NatoBoram/eldarya-enhancements/-/jobs/artifacts/$CI_COMMIT_TAG/raw/dist/eldarya-enhancements.min.user.js?job=deploy"
          link_type: "package"
        - name: "eldarya-enhancements-$CI_COMMIT_TAG.user.js"
          url: "https://gitlab.com/NatoBoram/eldarya-enhancements/-/jobs/artifacts/$CI_COMMIT_TAG/raw/dist/eldarya-enhancements.user.js?job=deploy"
          link_type: "package"
