include:
  - template: Dependency-Scanning.gitlab-ci.yml

default:
  image: node:latest

before_script:
  - npm ci

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules

build:
  stage: build
  script:
    - npx webpack
  except:
    - master
    - develop
    - tags

eslint:
  stage: test
  script:
    - npx eslint .

prettier:
  stage: test
  script:
    - npx prettier --check .

tsc:
  stage: test
  script:
    - npx tsc --noEmit

deploy:
  stage: deploy
  script:
    - npx webpack
  only:
    - master
    - develop
    - tags
  artifacts:
    paths:
      - dist/eldarya-enhancements.user.js
