export enum BodyLocation {
  All = "",
  Underwear = 1,
  Skins = 2,
  Tattoos = 20,
  Mouths = 21,
  Eyes = 3,
  Hair = 4,
  Socks = 5,
  Shoes = 6,
  Pants = 7,
  HandAccessories = 8,
  Tops = 9,
  Coats = 10,
  Gloves = 11,
  Necklaces = 12,
  Dresses = 13,
  Hats = 14,
  FaceAccessories = 15,
  Funds = 16,
  Belts = 18,
  Atmospheres = 19,
}
